workspace:
  base: /go
  path: src/github.com/drone/drone-runtime

pipeline:
  deps:
    image: golang:1.11
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  test:
    image: golang:1.11
    commands:
      - go test -v --cover ./...
